// Generated by AI
// I would have made this myselfd but I don't have access to my DAW rn since I don't have a windows SSD yet and I can't run a VM due to latency

function playBootChime() {
  const ctx = new (window.AudioContext || window.webkitAudioContext)();
  const now = ctx.currentTime;
  const DETUNE_CENTS = -30;

  // Master Gain Node
  const masterGain = ctx.createGain();
  masterGain.gain.setValueAtTime(0.0001, now);

  // Equalization Filters
  const bassShelf = ctx.createBiquadFilter();
  bassShelf.type = "lowshelf";
  bassShelf.frequency.value = 180;
  bassShelf.gain.value = 7;

  const brightness = ctx.createBiquadFilter();
  brightness.type = "lowpass";
  brightness.frequency.value = 7000;

  // Dynamics Compressor
  const compressor = ctx.createDynamicsCompressor();
  compressor.threshold.value = -18;
  compressor.knee.value = 20;
  compressor.ratio.value = 4;
  compressor.attack.value = 0.01;
  compressor.release.value = 0.3;

  // Audio Graph Routing
  masterGain.connect(bassShelf);
  bassShelf.connect(brightness);
  brightness.connect(compressor);
  compressor.connect(ctx.destination);

  // Master Volume Envelope
  masterGain.gain.exponentialRampToValueAtTime(0.8, now + 0.12);
  masterGain.gain.exponentialRampToValueAtTime(0.55, now + 1.0);
  masterGain.gain.exponentialRampToValueAtTime(0.0001, now + 4.5);

  // Tone Definition Data
  const chordNotes = [
    { freq: 138.591, gain: 0.5 },
    { freq: 184.997, gain: 0.9 },
    { freq: 233.082, gain: 0.55 },
    { freq: 277.183, gain: 0.45 },
    { freq: 369.994, gain: 0.55 },
    { freq: 466.164, gain: 0.4 },
  ];
  const bassFreqs = [46.249, 92.499];

  // Synthesize Bass Foundation
  bassFreqs.forEach((freq, i) => {
    const sub = ctx.createOscillator();
    sub.type = "sine";
    sub.frequency.value = freq;
    sub.detune.value = DETUNE_CENTS;

    const saw = ctx.createOscillator();
    saw.type = "sawtooth";
    saw.frequency.value = freq;
    saw.detune.value = DETUNE_CENTS;

    const sawFilter = ctx.createBiquadFilter();
    sawFilter.type = "lowpass";
    sawFilter.Q.value = 1.2;
    sawFilter.frequency.setValueAtTime(1400, now);
    sawFilter.frequency.exponentialRampToValueAtTime(320, now + 0.35);

    const sawGain = ctx.createGain();
    sawGain.gain.value = 0.4;

    const bassGain = ctx.createGain();
    const level = 0.9 / (i + 1);
    bassGain.gain.setValueAtTime(0.0001, now);
    bassGain.gain.exponentialRampToValueAtTime(level, now + 0.15);
    bassGain.gain.exponentialRampToValueAtTime(0.0001, now + 4.2);

    sub.connect(bassGain);
    saw.connect(sawFilter);
    sawFilter.connect(sawGain);
    sawGain.connect(bassGain);
    bassGain.connect(masterGain);

    sub.start(now);
    sub.stop(now + 4.5);
    saw.start(now);
    saw.stop(now + 4.5);
  });

  // Synthesize Harmonic Chords with Frequency Modulation (FM)
  chordNotes.forEach(({ freq, gain }, i) => {
    [-4, 4].forEach((chorusDetune) => {
      const carrier = ctx.createOscillator();
      carrier.type = "sine";
      carrier.frequency.value = freq;
      carrier.detune.value = DETUNE_CENTS + chorusDetune;

      const modulator = ctx.createOscillator();
      modulator.type = "sine";
      modulator.frequency.value = freq * 3.5;
      modulator.detune.value = DETUNE_CENTS;

      const modGain = ctx.createGain();
      modGain.gain.setValueAtTime(freq * 1.8, now);
      modGain.gain.exponentialRampToValueAtTime(2, now + 0.35);

      modulator.connect(modGain);
      modGain.connect(carrier.frequency);

      const voiceGain = ctx.createGain();
      voiceGain.gain.setValueAtTime(0.0001, now);
      voiceGain.gain.exponentialRampToValueAtTime(
        gain * 0.45,
        now + 0.13 + i * 0.01
      );
      voiceGain.gain.exponentialRampToValueAtTime(0.0001, now + 4.3);

      carrier.connect(voiceGain);
      voiceGain.connect(masterGain);

      modulator.start(now);
      modulator.stop(now + 4.5);
      carrier.start(now);
      carrier.stop(now + 4.5);
    });
  });

  // Synthesize Initial Transient White Noise ("Chiff")
  const noiseBufferSize = Math.floor(ctx.sampleRate * 0.08);
  const noiseBuffer = ctx.createBuffer(1, noiseBufferSize, ctx.sampleRate);
  const noiseData = noiseBuffer.getChannelData(0);

  for (let i = 0; i < noiseBufferSize; i++) {
    noiseData[i] = Math.random() * 2 - 1;
  }

  const noise = ctx.createBufferSource();
  noise.buffer = noiseBuffer;

  const chiffFilter = ctx.createBiquadFilter();
  chiffFilter.type = "bandpass";
  chiffFilter.frequency.value = 700;
  chiffFilter.Q.value = 0.7;

  const chiffGain = ctx.createGain();
  chiffGain.gain.setValueAtTime(0.25, now);
  chiffGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.08);

  noise.connect(chiffFilter);
  chiffFilter.connect(chiffGain);
  chiffGain.connect(bassShelf);

  noise.start(now);
}
